spring.application.name=low-latency-ai

ai.loader.model=file:../../models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/model.onnx
ai.loader.tokenizer=file:../../models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/tokenizer.json

spring.data.gemfire.pool.locators=localhost[10334]

logging.level.org.springframework.modulith=DEBUG
logging.level.org.apache.geode.cache.client.internal.AbstractOp=DEBUG
